   <div id="me" class="tabs" data-id="top">
   <div class="noti">
      <center>
      <div  class="icon" data-id="friends"><i class="fas fa-user-friends"></i></div>
      <div class="icon" data-id="search"><i class="fas fa-search"></i></div>
      <div class="icon" data-id="money"><i class="fas fa-money-bill-wave"></i></div>
      <div class="icon" data-id="settings"><i class="fas fa-cogs"></i></div>
      <div class="icon" data-id="logout"><i class="fas fa-sign-out-alt"></i></div>
      </center>
   </div>
   <div class="search">
      <input type="text" placeholder="Buscar">
      <button class="btn"><i class="fas fa-search"></i></button>
   </div>

   <div class="profile_foo" style="background: rgb(57, 63, 74); width: 100%; height: 200px; padding: 5px 0px">
      <div class="back_profile"></div>
      <div class="status">
      <img style="z-index: 100; position: relative;width: 80px; height: 80px; border-radius: 10px; transition: 0.4s;" src="<?php echo $avatar;?>"/>
      <span style="color: var(--white2); position: relative; top: -50px; left: 10px; font-size: 22px;"><?php echo $name_full;?></span>
      <span style="color: var(--white2); position: absolute; top: 45px; left: 95px; font-size: 17px;">Um mero ser comum</span>
      </div>
   </div>

   

</div>