   <div id="me" class="tabs" data-id="top">
   <div class="noti">
      <center>
      <div  class="icon" data-id="friends"><i class="fas fa-user-friends"></i></div>
      <div class="icon" data-id="search"><i class="fas fa-search"></i></div>
      <div class="icon" data-id="money"><i class="fas fa-money-bill-wave"></i></div>
      <div class="icon" data-id="settings"><i class="fas fa-cogs"></i></div>
      <a href="/logout?token=<?php echo sha1($_COOKIE['iduser']);?>"> <div class="icon" data-id="logout"><i class="fas fa-sign-out-alt"></i></div></a>
      </center>
   </div>
   <div class="search">
      <input type="text" placeholder="Buscar">
      <button class="btn"><i class="fas fa-search"></i></button>
   </div>

   <div v-if="!vendoEstrando"  class="profile_foo" style="background: rgb(57, 63, 74); width: 100%; height: 200px; padding: 5px 0px">
      <div class="back_profile"></div>
      <div class="status">
      <img style="z-index: 100; position: relative;width: 80px; height: 80px; border-radius: 10px; transition: 0.4s;" src="<?php echo $avatar;?>"/>
      <span style="color: var(--white2); position: relative; top: -50px; left: 10px; font-size: 22px;">
      <div class="loading" v-if="myProfile.nome == '' || myProfile.nome == null" style="
      top: -20px;
      width: 50%;
      height: 20px;
      background: var(--dark1);
      position: relative;
      left: 85px;"></div>
      {{ myProfile.nome }}
      </span>
      <span style="color: var(--white2); position: absolute; top: 45px; left: 95px; font-size: 17px;">Um mero ser comum</span>
      </div>
   </div>

   <div v-else="" class="profile_foo" style="top: 46px;background: rgb(57, 63, 74); width: 100%; height: 200px; padding: 5px 0px">
   <div style="position: relative;
    color: #fff;
    background: var(--button-border);
    text-align: center;
    padding: 5px;"> Vendo perfil de {{ estranhoProfile.nome }}</div>
   <button style="z-index: 550;
    position: absolute;
    top: 48px;
    border-radius: 50%;
    height: auto;
    width: auto;
    padding: 7px;
    background: var(--blue);
    box-shadow: 1px 2px 1px rgba(0,0,0,.20);
    left: 11px;
    cursor: pointer;" @click="vendoEstrando = false"><i class="fas fa-arrow-left"></i></button>
      <div class="back_profile"></div>
      <div class="status">
      <img style="z-index: 100; position: relative;width: 80px; height: 80px; border-radius: 10px; transition: 0.4s;" src="<?php echo $avatar;?>"/>
      <span style="color: var(--white2); position: relative; top: -50px; left: 10px; font-size: 22px;">
      <div class="loading" v-if="estranhoProfile.nome == '' || estranhoProfile.nome == null" style="
      top: -20px;
      width: 50%;
      height: 20px;
      background: var(--dark1);
      position: relative;
      left: 85px;"></div>
      {{ estranhoProfile.nome }}
      </span>
      <span style="color: var(--white2); position: absolute; top: 45px; left: 95px; font-size: 17px;">Um mero ser comum</span>
      </div>
   </div>

   

</div>