   <div id="me" class="tabs" data-id="top">
   <img src="images/00be7f6ca68f1915a80ae01f061718e5.svg" style="width: 105%; height: auto; position: absolute; top: 200px; left: 0px;" alt="">
   <div class="noti">
      <center>
      <div  class="icon" data-id="friends"><i class="fas fa-user-friends"></i></div>
      <div class="icon" @click="search = true" data-id="search"><i class="fas fa-search"></i></div>
      <div class="icon" data-id="money"><i class="fas fa-money-bill-wave"></i></div>
      <div class="icon" data-id="settings"><i class="fas fa-cogs"></i></div>
      <a href="/logout?token=<?php echo sha1($_COOKIE['iduser']);?>"> <div class="icon" data-id="logout"><i class="fas fa-sign-out-alt"></i></div></a>
      </center>
   </div>
   <div class="search" v-bind:class="{ searchAtivo: search }">
      <input v-model="searchTerm" @blur="search = false" type="text" placeholder="Buscar">
      <button class="btn"><i class="fas fa-search"></i></button>
   </div>

   <div class="mencionar scrollar" v-if="search" style="top: 79px;
    z-index: 1000;
    max-height: 100%;
    background: #26272b;
    z-index: 50000 !important;">
    <h1 style="padding: 10px; font-size: 18px;">Buscas para {{ searchTerm }} </h1>
         <div @click="verEstranho(user)" class="user" v-for="user in users" v-if="user.nome.includes(searchTerm.replace('@', ''))">
         
          <p > <img style="height: 38px;
         width: 38px;
         position: absolute;
         top: 0px;
         left: 0px;" v-if="user.avatar == ''" src="/themes/avatar.png" alt=""> <img style="height: 38px;
         width: 38px;
         position: absolute;
         top: 0px;
         left: 0px;" v-if="user.avatar !== ''" :src="user.avatar" alt=""> {{ user.nome }}</p>
         </div>
   </div>

   <div v-if="!vendoEstrando"  class="profile_foo" style="background: rgb(57, 63, 74); width: 100%; height: 200px; padding: 5px 0px">
      <div class="back_profile"></div>
      <div class="status">
      <img style=" z-index: 100; position: relative;width: 80px; height: 80px; border-radius: 10px; transition: 0.4s;"  src="/themes/avatar.png">
      <img v-if="!myProfile.avatar == ''" style="z-index: 100;
    position: relative;
    width: 80px;
    height: 80px;
    border-radius: 10px;
    transition: all 0.4s ease 0s;
    position: absolute;
    left: 0px;" src="/themes/avatar.png" :src="myProfile.avatar">
      </img>
      <span style="color: var(--white2); position: relative; top: -50px; left: 10px; font-size: 22px;">
      <div class="loading" v-if="myProfile.nome == '' || myProfile.nome == null" style="
      top: -20px;
      width: 50%;
      height: 20px;
      background: var(--dark1);
      position: relative;
      left: 85px;"></div>
      {{ myProfile.nome }}
      </span>
      <span style="color: var(--white2); position: absolute; top: 45px; left: 95px; font-size: 17px;">Um mero ser comum</span>
      </div>

   <div class="newN" style="
    color: var(--white2);
    position: absolute;
    top: 210px;
    padding: 25px 24px 0px;
    height: calc(100% + 430px);
    width: calc(94% - 30px);">
    <button v-bind:class="{newsNAtivo: notificationWhere == 0}" @click="notificationWhere = 0">
    <i class="fas fa-bell"></i>
    <div class="count_b" v-if="notifications[0].count > 0">
       <span v-if="notifications[0].count >= 99">+99</span> <span v-else="">{{ notifications[0].count }}</span>
      </div>
    </button>
    <button v-bind:class="{newsNAtivo: notificationWhere == 1}" @click="notificationWhere = 1">
    <i class="fas fa-comments"></i>
    <div class="count_b" v-if="notifications[1].count > 0">
       <span v-if="notifications[1].count >= 99">+99</span> <span v-else="">{{ notifications[1].count }}</span>
      </div>
    </button>
   <div v-if="notificationWhere == 0">
   <h1 style="font-size: 22px;">Notificações</h1>
   <span style="padding: 0px; font-size: 23px; margin-top: 20px; position: relative; top: 30px;" v-if="notifications[0].count == 0">
      Nenhuma notificação
   </span>
   <div class="scroll">
   <div v-for="user in users">
   <li v-for="friend in newsBa" 
   v-if="friend.id_quem == myProfile.id && friend.ativo == 1 && friend.aceito == 0 && user.id == friend.id_user"
   @click="verEstranho(user)"
   style="list-style: none;
    background: var(--dark1);
    padding: 20px;
    position: relative;
    left: -9px;
    width: 78%;
    margin-top: 10px;
    border-radius: 3px;
    cursor: pointer;">
      <img style="height: 38px;
    width: 38px;
    position: absolute;
    top: -6px;
    left: 11px;" src="/themes/avatar.png" alt="">
    <span style="left: 40px; position: relative; top: -15px;">{{ user.nome }}</span>
         <p style="left: -8px;
    position: relative;
    white-space: pre-wrap;
    top: 3px;
    width: 100%;">Te mandou uma solitação de amizade</p>
   </li>
   </div>
   </div>
   </div>

   <div v-if="notificationWhere == 1">
   <h1 style="font-size: 22px;">Mensagens</h1>

   <div class="scroll">
   <li style="list-style: none;
    background: var(--dark1);
    padding: 20px;
    position: relative;
    left: -9px;
    width: 78%;
    margin-top: 10px;
    border-radius: 3px;
    cursor: pointer;">
      <img style="height: 38px;
    width: 38px;
    position: absolute;
    top: -6px;
    left: 11px;" src="/themes/avatar.png" alt="">
    <span style="left: 40px; position: relative; top: -15px;">Alexandre Silva</span>
         <p style="left: -8px;
    position: relative;
    white-space: pre-wrap;
    top: 3px;
    width: 100%;">Oii</p>
   </li>
   </div>
   </div>

   </div>

   </div>

   <div v-else="" class="profile_foo" style="top: 46px;background: rgb(57, 63, 74); width: 100%; height: 200px; padding: 5px 0px">
   <div style="position: relative;
    color: #fff;
    background: var(--button-border);
    text-align: center;
    padding: 5px;"> Vendo perfil de {{ estranhoProfile.nome }}</div>
   <button style="z-index: 550;
    position: absolute;
    top: 48px;
    border-radius: 50%;
    height: auto;
    width: auto;
    padding: 7px;
    background: var(--blue);
    box-shadow: 1px 2px 1px rgba(0,0,0,.20);
    left: 11px;
    cursor: pointer;" @click="vendoEstrando = false"><i class="fas fa-arrow-left"></i></button>
      <div class="back_profile"></div>
      <div class="status">
      <img v-if="estranhoProfile.avatar !==  ''" style="z-index: 100; position: relative;width: 80px; height: 80px; border-radius: 10px; transition: 0.4s;" :src="estranhoProfile.avatar"/>
      <img v-if="estranhoProfile.avatar ===  ''" style="z-index: 100; position: relative;width: 80px; height: 80px; border-radius: 10px; transition: 0.4s;" src="/themes/avatar.png"/>
      <span style="color: var(--white2); position: relative; top: -50px; left: 10px; font-size: 22px;">
      <div class="loading" v-if="estranhoProfile.nome == '' || estranhoProfile.nome == null" style="
      top: -20px;
      width: 50%;
      height: 20px;
      background: var(--dark1);
      position: relative;
      left: 85px;"></div>
      {{ estranhoProfile.nome }}
      </span>
      <span style="color: var(--white2); position: absolute; top: 45px; left: 95px; font-size: 17px;">Um mero ser comum</span>
      </div>

   <div style="
    position: relative;
    top: -112px;
    left: 20px;
    width: auto;">
   <button style="background: var(--button-color);
    border: none;
    color: var(--white);
    padding: 3px;
    font-size: 22px;
    border-radius: 20px;
    padding: 10px;
    cursor: pointer;" @click="chatComUser(estranhoProfile)"><i class="far fa-comment-dots"></i></button>
    <button style="background: var(--button-color);
    border: none;
    color: var(--white);
    padding: 3px;
    font-size: 22px;
    border-radius: 20px;
    padding: 10px;
    cursor: pointer;"><i class="fas fa-thumbs-up"></i></button>

    <button v-if="friends.find((friend) => friend.id_quem === estranhoProfile.id && friend.id_user == myProfile.id && friend.aceito == 1)"  @click="addFriend(estranhoProfile.id)" style="background: var(--button-color);
    border: none;
    color: var(--white);
    padding: 3px;
    font-size: 22px;
    border-radius: 20px;
    padding: 10px;
    cursor: pointer;"><i class="fas fa-user-times"></i></button>
    <button v-else-if="friends.find((friend) => friend.id_quem == estranhoProfile.id && friend.id_user == myProfile.id && friend.aceito == 0)" @click="addFriend(estranhoProfile.id)" style="background: var(--button-color);
    border: none;
    color: var(--white);
    padding: 3px;
    font-size: 22px;
    border-radius: 20px;
    padding: 10px;
    cursor: pointer;"><i class="fas fa-user-slash"></i></button>
    <button v-else-if="friends.find((friend) => friend.id_quem == myProfile.id && friend.id_user == estranhoProfile.id && friend.aceito == 0)"
       @click="aceitarAmigo(estranhoProfile.id)" style="background: var(--button-color);
    border: none;
    color: var(--white);
    padding: 3px;
    font-size: 22px;
    border-radius: 20px;
    padding: 10px;
    cursor: pointer;"><i class="fas fa-user-check"></i></button>
    <button v-else-if="friends.find((friend) => friend.id_quem == myProfile.id && friend.id_user == estranhoProfile.id && friend.aceito == 1)" 
       @click="addFriend(estranhoProfile.id)" style="background: var(--button-color);
    border: none;
    color: var(--white);
    padding: 3px;
    font-size: 22px;
    border-radius: 20px;
    padding: 10px;
    cursor: pointer;"><i class="fas fa-user-slash"></i></button>
    <button v-else="" @click="addFriend(estranhoProfile.id)" style="background: var(--button-color);
    border: none;
    color: var(--white);
    padding: 3px;
    font-size: 22px;
    border-radius: 20px;
    padding: 10px;
    cursor: pointer;"><i class="fas fa-user-plus"></i></button>
    </div>


   </div>

   

</div>