<div id="feed" class="tabs">
   <div class="feed">
      <span><i class="fas fa-home"></i>     Mensagem/Grupo</span>
   </div>
  <div class="list_feed">
      <p>Sem nenhuma mensagem</p>
   </div>
   <div class="bottom">
   	<div class="post">
      <textarea name="" id="" cols="30" rows="10" placeholder="Envie uma mensagem" style="position: absolute; left: 0px; top: 0px; height: 100%; padding: 10px; top: 0px;"></textarea>
      <button style="position: absolute; bottom: 0px; float: right; right: 0px; background: #4f6ea7; padding: 8px; cursor: pointer; outline: none; box-shadow: 2px 2px 1px rgba(0,0,0,.40);"><i class="fas fa-paper-plane"></i></button>
   </div>
   </div>
</div>