<div id="feed" class="tabs">
   <div class="feed">
      <span><i class="fas fa-server"></i>          <nani id="group">Chat geral</nani> / Chat geral</span>
   </div>
   <div class="list_feed">
      <p>Sem nenhuma mensagem no momento :/</p>
   </div>
   <div class="bottom">
   <div class="post">
      <input name="" id="" cols="30" rows="10" placeholder="Enviei uma mensagem" style="position: absolute; left: 0px; top: 0px; height: 100%; padding: 10px; top: 0px; width: 100%; padding-right: 40px; background: transparent; color: #fff; font-size: 18px;"/>
      <button style="position: absolute; bottom: 0px; float: right; right: 0px; background: #4f6ea7; padding: 8px; cursor: pointer; outline: none; box-shadow: 2px 2px 1px rgba(0,0,0,.40);"><i class="fas fa-paper-plane"></i></button>
   </div>
   </div>
</div>