<div id="feed" class="tabs">
   <div class="feed">
      <span><i class="fas fa-server"></i>          <nani id="group">{{ selectServer.name }}</nani> / Chat geral</span>
      <span style="
         float: right;
         top: 0px;
         cursor: pointer;
      "
      @click="options = true"
      ><i class="fas fa-ellipsis-h"></i></span>
   </div>
   <div class="list_feed">
 
      <p v-if="mensagem.length == 0">Sem nenhuma mensagem no momento :/</p>
      <p v-if="mensagem.length > 0" class="animation_a" v-for="msg in mensagem">
      <span v-for="user in users">
      <span v-if="user.id === msg.id_user"> 
      <span v-if="user.id === selectServer.owner " style="
         background: var(--blue);
         position: absolute;
         left: 23px;
         top: -10px;
         z-index: 100;
         color: #fff;
         font-size: 18px;
         padding: 2px;
         border-radius: 1px;
      "><i class="fab fa-jedi-order"></i></span>
      <img v-if="user.avatar == '' || user.avatar == null" style="
         width: 35px;
         height: 35px;
         border-radius: 5px;
         position:absolute;
         top: -18px;
         left: 0px;
         margin: 5px;
         border: 3px solid var(--dark1);" src="/themes/avatar.png" alt="">
      {{ user.nome }} - </span> </span>  {{  msg.mensagem }}</p>
     
   </div>

   <div class="bottom">
   <div class="post">
      <input v-model="msg" @keyup.Enter="sendMsg" name="" id="" cols="30" rows="10" placeholder="Envie uma mensagem" style="position: absolute; left: 0px; top: 0px; height: 100%; padding: 10px; top: 0px; width: 100%; padding-right: 40px; background: transparent; color: #fff; font-size: 18px;"/>
      <button  @click="sendMsg" style="
      position: absolute;
    float: right;
    right: 0px;
    background: rgb(79, 110, 167);
    padding: 10px;
    cursor: pointer;
    outline: none;
    box-shadow: rgba(0, 0, 0, 0.4) 2px 2px 1px;
    margin: 0px -1px;"><i class="fas fa-paper-plane"></i></button>
   </div>

   </div>
  
</div>